### PR TITLE
Increase scheduler sleep frequency

### LINKED ISSUE #134: High CPU usage while waiting for cron schedule
I noticed a high CPU usage - even though it should not be doing anything but waiting for the cron scheduled time.

In the Rufus scheduler there is a :frequency option which by default is 0.3s - could this be increased here? Maybe this would help?

### PR DESCRIPTION
**Pull request by suyograo**
Fixes #134

Rufus: https://github.com/jmettraux/rufus-scheduler#rufusschedulernew-options

### CODE REVIEW

**Comment by mrjameshamilton** [comment]
will this be released?

**Comment by guyboertje** [comment]
@suyograo - After seeing a customer using a 2 second cron schedule, i'm concerned.
We could parse the cron schedule string looking for seconds and not set frequency - wdyt?

**Comment by jordansissel** [comment]
@guyboertje I agree with you.

I'll follow up on the parent ticket. I have ideas for rufus.

**Comment by jordansissel** [comment]
I commented - https://github.com/logstash-plugins/logstash-input-jdbc/issues/134#issuecomment-300517503

At this time, I do not believe we have enough information to decide that rufus's check frequency is the problem, so I would decline this patch.

**Comment by jordansissel** [comment]
I'm closing this for two reasons:

1) The 30 second time will likely make it impossible for users who are currently using cron schedule per-second such as every-2-seconds

2) I am not seeing data pointing that rufus is the reason for high cpu. Let's track #134 and find the origin of the issue.

**Pull request closed without merging**
