### PR TITLE
Update jdbc.rb

### PR DESCRIPTION
**Pull request by lovejeet**
Added the description for sql_last_value as explained by untergeek here https://github.com/logstash-plugins/logstash-input-jdbc/issues/57.

### CODE REVIEW

**Comment by untergeek** [comment]
@lovejeet We're going to document this more fully in a blog post.  What I wrote in #57 is not intended to be the documentation for the plugin.

**Comment by suyograo** [comment]
The docs have been updated

**Comment by ppamulapati** [comment]
I am new to logstash. can someone please help on upgrade steps for JDBC input plugin.

**Comment by untergeek** [comment]
@ppamulapati GitHub is not the proper place for usage questions.  Please look to https://discuss.elastic.co/c/logstash for usage questions.  This one may be already answered there.

**Pull request closed without merging**
