### PR TITLE
Manually take care of the pagination instead of using Sequel

### PR DESCRIPTION
**Pull request by chaodhib**
Fixes https://github.com/logstash-plugins/logstash-input-jdbc/issues/166

As explained [here](https://github.com/logstash-plugins/logstash-input-jdbc/issues/166#issuecomment-325975178), Sequel does not parse any native SQL given to it. Therefore, it does not add properly the LIMIT and OFFSET clauses. The only solution is to do it manually. It's the approach I took.

Apologies in advance for the code. I don't usually program in Ruby.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @chaodhib, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-input-jdbc/pull/232.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by chaodhib** [comment]
@Hi. My apoligies. I will take care of that shortly.

**Comment by chaodhib** [comment]
Done.

**Comment by chaodhib** [comment]
I'm not really sure why I have a failing test. It may be because the LIMIT or the OFFSET clause does not work on every DB and to be more specific on the database used for the test?

**Comment by guyboertje** [comment]
Yep, screwed.

We chose to specify a SQL statement as it is the most flexible arrangement.

**Pull request closed without merging**
