### PR TITLE
Provide a fix for RubyTime conversion

### LINKED ISSUE #77: RubyTime object is not Logstash::Timestamp
It appears that the JDBC plugin is grabbing timestamps correctly, but it's only converting them to `RubyTime` objects, which is not the same thing as a `Logstash::Timestamp`.  This conversion should be possible without resorting to a `ruby{}` filter.

See: https://discuss.elastic.co/t/logstash-date-filter-question/33663

### PR DESCRIPTION
**Pull request by purbon**
Fix #77 by adding some decoration/conversion when need.

### CODE REVIEW

**Comment by purbon** [comment]
@talevy happy if you can give me your thoughts on this.

**Comment by suyograo** [comment]
nice!

**Comment by jordansissel** [comment]
Code LGTM; haven't tested. Nice refactoring along with the fix! :)

**Comment by suyograo** [comment]
@purbon curious if there is a performance hit of this? going through every field and checking if its a time value? 

Also, on a related note, sequel exposes this option `:convert_types`:

> If set to false, does not attempt to convert some Java types to ruby types. Setting to false roughly doubles performance when selecting large numbers of rows. Note that you can't provide this option inside the connection string (as that is passed directly to JDBC), you have to pass it as a separate option.

See http://sequel.jeremyevans.net/rdoc/files/doc/opening_databases_rdoc.html#label-jdbc+

Should we explore this?

**Comment by purbon** [comment]
@suyograo no doubt we should explore performance on this.

re: not changing previous looping behaviour to check for time, just adding a conversion when need ( I expect not a lot of impact as it was done before just to convert keys to strings).

**Comment by suyograo** [comment]
+1, I'll open a new issue for using `:convert_types`

**Comment by jordansissel** [comment]
> curious if there is a performance hit of this?

We could also take a similar approach to Elasticsearch's dynamic mapping - cache previously-unknown column/field names by type. Should be faster than checking each column/field every event, but i'm open to having it be explicit (even if just for a little while) to start with.

**Comment by suyograo** [comment]
+1 on merging this for a first iteration. We can always make it faster :)

**Comment by talevy** [comment]
@jordansissel PR has build check, no need to test!

LGTM

**Pull request closed without merging**
