### PR TITLE
auto reconnect

### PR DESCRIPTION
**Pull request by tac0x2a**
I implemented auto reconnect to database in running. 

If disconnected to database, it will attempt close and re-open connection.

### CODE REVIEW

**Comment by minibbjd** [comment]
I've tried this with a jdbc oracle input that is scheduled to fetch every seconds. When I shutdown and restart the database, the reconnect doesn't return from Sequel.connect(@jdbc_connection_string, opts=opts). 

I've tried using 

        sequel_opts => {login_timeout => 5 }

but that didn't help.

**Comment by tac0x2a** [comment]
Hi, @minibbjd 

Thank you for reviewing my PR.
I fix the issue by closing `@database` and assign `nil` to `@database` when failed `@database.test_connection()`, instead of you shown it.

Could you check the new commit c80533a .

Regards.

**Comment by djgerhab** [comment]
I do believe this would solve [Open issue 45](https://github.com/logstash-plugins/logstash-input-jdbc/issues/45)

@tac0x2a, @minibbjd Thanks for working on this. I'm new to this codebase and jruby so I wouldn't be knowledgeable enough to attempt to fix the CI failures but looking forward to having this logstash plugin db connect errors resolved!

**Comment by tac0x2a** [comment]
Hi @djgerhab  , Thank you for expecting this PR. I will fix the CI failures. Please wait !

**Comment by tac0x2a** [comment]
Hi @minibbjd , I fixed tests. Could you consider merge this PR ?

**Comment by andrewvc** [comment]
This is awesome. LGTM! :)

**Comment by saifrehman15** [comment]
I have almost same error.
`[INFO ] 2019-10-16 15:42:52.729 [Ruby-0-Thread-1: /usr/share/logstash/lib/bootstrap/environment.rb:6] agent - Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[INFO ] 2019-10-16 15:42:53.259 [Api Webserver] agent - Successfully started Logstash API endpoint {:port=>9600}
[INFO ] 2019-10-16 15:42:54.674 [[main]<fayvo] fayvo - (0.021805s) select * from user_posts where id > 0 limit 0 ,10 
[WARN ] 2019-10-16 15:42:54.822 [[main]<fayvo] fayvo - Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::JavaSql::SQLException: Value '2media$3aae68f5-38b4-11e9-b66c-0af13b44a73a311
Mango Duckï¿½0Aï¿½0ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½51.5045-0.08652017-01-17 20:49:092019-03-07 12:49:380000-00-00 00:00:0031484686149-2-m7M96960001' can not be represented as java.sql.Timestamp>}
[INFO ] 2019-10-16 15:42:55.187 [[main]-pipeline-manager] pipeline - Pipeline has terminated {:pipeline_id=>"main", :thread=>"#<Thread:0x4252699b run>"}
[INFO ] 2019-10-16 15:42:55.498 [LogStash::Runner] runner - Logstash shut down.
`

**Pull request closed without merging**
