### PR TITLE
Fix jdbc_paging_enabled config flag not being passed through

### PR DESCRIPTION
**Pull request by bmax**
fixes https://github.com/logstash-plugins/logstash-input-jdbc/issues/360

Not a ruby developer by trade so having trouble making the test better.

First PR. I signed CLA after I made this. 
cc @guyboertje

### CODE REVIEW

**Comment by bmax** [comment]
@robbavey Any help?

**Comment by robbavey** [comment]
@bmax - This has been merged and included in the latest `4.3.19` release of the JDBC input. Thanks again for your contribution!

**Comment by bmax** [comment]
woohoo @robbavey! Super excited, thanks. How does the default version that gets included with Logstash's Dockerfile get updated?

**Comment by robbavey** [comment]
@bmax Logstash (including the docker image) is released at the same time as the rest of the Elastic stack, and this change will be included in a future release.
However, we don't tend to give out dates and the exact release version that changes will be released in ahead of time.

**Pull request merged**
